name: If Demo at Job Level
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build_deploy.yaml"
  pull_request: 
    paths:
      - ".github/workflows/build_deploy.yaml"
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Build Application
        run: echo "Building the application"
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - name: Deploy Application
        run: echo "Deploying the application"
        
