name: Demo of Context Variables
on: 
  push:
    paths:
      - ".github/workflows/context_var.yaml"
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Using the context variables
        run: |
          echo "This workflow is triggered by '${{ github.actor }}'"
          echo "The repository is '${{ github.repository }}'"
          echo "The branch is '${{ github.ref_name }}'"

      - name: Print all variables under github.
        run: |
          echo "The github variables are in the below...!!!"
          echo "${{ toJson(github) }}"

      - name: Print environment varibles
        run: |
        echo "The Environment variables list is"
        echo "$GITHUB_SHA"

      
          
