name: Demo of If along with Or
on:
  push:
    paths:
      - ".github/workflows/if_along_with_or.yaml"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        if: github.actor == 'avk' || github.actor == 'avk-git-07'
        run: echo "The user is either 'avk' or 'avk-git-07'"
        
        
      
