name: Demo of If Condition
on: 
  push:
    paths:
      - ".github/workflows/if_demo.yaml"
    branches:
      - main  
      - development
jobs:
  if_demo:
    runs-on: ubuntu-latest
    steps:
      - name: If Demo
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "Run this 'If Demo' step"
        
