name: Demo of If Condition
on: 
  push:
    paths:
      - ".github/workflows/if_demo.yaml"
    branches:
      - main  
      - development
jobs:
  if_demo:
    runs-on: ubuntu-latest
    steps:
      - name: If the branch is main
        if: github.ref_name == 'main'
        run: echo "Runnig this step for the 'main' branch"
      - name: No condition step
        run: echo "Running this step where there is no condition"
        
