name: Demo of outputs
on: 
  push:
    paths:
      - ".github/workflows/outputs.yaml"
jobs:
  build:
    outputs:
      version_build: ${{ steps.build.outputs.version_1 }}
    runs-on: ubuntu-latest
    steps:
      - name: Build
        id: build
        run: echo "version_1= 0.0.1" >> $GITHUB_OUTPUT 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying the app with the latest version i.e., is ${{ needs.build.outputs.version_build }}"
        
  
